import mech from "@/assets/cat-mechanical.jpg";
import metal from "@/assets/cat-metal.jpg";
import inst from "@/assets/cat-instruments.jpg";
import office from "@/assets/cat-office.jpg";

export type CategoryKey = "mechanical" | "metal" | "instruments" | "office";

export const CATEGORIES: { key: CategoryKey; en: string; zh: string; image: string }[] = [
  { key: "mechanical", en: "Mechanical Equipment", zh: "机械设备", image: mech },
  { key: "metal", en: "Metal Products", zh: "金属制品", image: metal },
  { key: "instruments", en: "Instruments / Meters", zh: "仪器仪表", image: inst },
  { key: "office", en: "Office Equipment", zh: "办公设备", image: office },
];

const catImg: Record<CategoryKey, string> = {
  mechanical: mech,
  metal: metal,
  instruments: inst,
  office: office,
};

export const catLabel = (k: CategoryKey) => CATEGORIES.find((c) => c.key === k)!;

export type Product = {
  id: number;
  slug: string;
  nameEn: string;
  nameZh: string;
  category: CategoryKey;
  descEn: string;
  descZh: string;
  image: string;
  gallery: string[];
  features: { en: string; zh: string }[];
  specs: { label: { en: string; zh: string }; value: string }[];
  applicationsEn: string[];
  applicationsZh: string[];
  material?: string;
  usage?: string;
};

const specsBase = (code: string): Product["specs"] => [
  { label: { en: "Product Code", zh: "产品编号" }, value: code },
  { label: { en: "Origin", zh: "产地" }, value: "Shenzhen, China" },
  { label: { en: "MOQ", zh: "起订量" }, value: "Negotiable / 可议" },
  { label: { en: "Packaging", zh: "包装" }, value: "Export carton / 出口纸箱" },
  { label: { en: "Lead Time", zh: "交货期" }, value: "Subject to inquiry / 以询盘为准" },
];

function productAsset(file: string) {
  return new URL(`../assets/product/${file}`, import.meta.url).href;
}

function make(
  id: number,
  nameEn: string,
  nameZh: string,
  category: CategoryKey,
  descEn: string,
  descZh: string,
  features: [string, string][],
  applications: [string, string][],
  imageFile: string,
  galleryFiles: string[],
  extraSpecs: [string, string][] = [],
): Product {
  const slug = `hkd-${String(id).padStart(3, "0")}`;

  return {
    id,
    slug,
    nameEn,
    nameZh,
    category,
    descEn,
    descZh,
    image: productAsset(imageFile),
    gallery: [imageFile, ...galleryFiles].map(productAsset),
    features: features.map(([en, zh]) => ({ en, zh })),
    applicationsEn: applications.map(([en]) => en),
    applicationsZh: applications.map(([, zh]) => zh),
    specs: [
      { label: { en: "Product Code", zh: "产品编号" }, value: slug.toUpperCase() },
      ...extraSpecs.map(([label, value]) => ({
        label: { en: label, zh: label },
        value,
      })),
    ],
  };
}

export const PRODUCTS: Product[] = [
  make(
    1,
    "High Precision LCD Digital Vernier Caliper",
    "高精度LCD数显游标卡尺",
    "instruments",
    "High-precision stainless steel digital vernier caliper with LCD display, fine adjustment, and multiple length options for industrial measurement and workshop inspection.",
    "高精度不锈钢LCD数显游标卡尺，配有微调功能，并提供多种长度规格，适用于工业测量与车间检测。",
    [
      ["Accuracy 0.05mm", "精度0.05mm"],
      ["Stainless steel material", "不锈钢材质"],
      ["Fine adjustment design", "带微调功能"],
    ],
    [
      ["Industrial measurement", "工业测量"],
      ["Workshop inspection", "车间检测"],
      ["Precision parts checking", "精密零件检测"],
    ],
    "1.jpg",
    ["1.1.jpg", "1.2.jpg", "1.3.jpg", "1.4.jpg", "1.5.jpg"],
    [
      ["Length", "100mm / 150mm / 200mm / 300mm"],
      ["Material", "Stainless Steel"],
      ["Accuracy", "0.05mm"],
      ["Packing", "50PCS/CTN"],
      ["Carton Size", "55 × 34 × 23CM"],
      ["N.W.", "21KGS"],
      ["G.W.", "22KGS"],
    ],
  ),

  make(
    2,
    "DT830B Pocket Digital Multimeter",
    "DT830B便携式数字万用表",
    "instruments",
    "Pocket digital multimeter designed for measuring DC/AC voltage, current, and resistance, suitable for mobile phone repair, maintenance, and electrical testing.",
    "便携式数字万用表，适用于测量直流/交流电压、电流及电阻，可用于手机维修、设备维护及电气检测。",
    [
      ["LCD display 49 × 16mm", "49 × 16mm液晶显示屏"],
      ["Overload protection", "过载保护"],
      ["Low battery indication", "低电量提示"],
    ],
    [
      ["Mobile phone repair", "手机维修"],
      ["Electrical maintenance", "电气维护"],
      ["General testing work", "通用测试作业"],
    ],
    "2.jpg",
    ["2.1.jpg", "2.2.jpg", "2.3.jpg", "2.4.jpg"],
    [
      ["LCD Size", "49 × 16mm"],
      ["Max Display", "1999"],
      ["Power Supply", "One 9V 6F22 battery"],
      ["Product Size", "130 × 75 × 30mm"],
      ["DC Voltage", "200mV / 2000mV / 20V / 200V / 1000V"],
      ["AC Voltage", "200V / 750V"],
      ["Accessories", "Meter with battery, test lead, manual"],
    ],
  ),

  make(
    3,
    "DT9205A Industrial Handheld Digital Multimeter",
    "DT9205A工业手持式数字万用表",
    "instruments",
    "Professional industrial handheld digital multimeter with AC/DC voltage and current testing, resistance, capacitance, frequency, buzzer, data hold, and large LCD display.",
    "专业工业手持式数字万用表，支持交直流电压电流、电阻、电容、频率、蜂鸣通断、数据保持及大屏显示。",
    [
      ["Large 3.5 digit LCD display", "3.5位大屏LCD显示"],
      ["Continuity buzzer and data hold", "蜂鸣通断测试与数据保持"],
      ["Full protection fire-resistant design", "防火全保护设计"],
    ],
    [
      ["Industrial testing", "工业检测"],
      ["Equipment maintenance", "设备维护"],
      ["Electrical diagnostics", "电气诊断"],
    ],
    "3.jpg",
    ["3.1.jpg", "3.2.jpg"],
    [
      ["DCV", "200m / 2 / 20 / 200 / 1000V ±0.5%"],
      ["ACV", "200m / 2 / 20 / 200 / 750V ±1.0%"],
      ["DCA", "2m / 20m / 200m / 20A ±1.8%"],
      ["ACA", "2m / 20m / 200m / 10A ±2.0%"],
      ["Resistance", "200Ω / 2K / 20K / 200K / 2M / 20MΩ / 200MΩ ±1.0%"],
      ["Capacitance", "20n / 200n / 2u / 20u / 200uF ±4.0%"],
      ["Max Display", "1999"],
      ["Power Supply", "One 9V 6F22 battery"],
      ["Accessories", "Meter with battery, holster, test lead, gift box, manual"],
    ],
  ),

  make(
    4,
    "60m Digital Laser Distance Meter",
    "60米数显激光测距仪",
    "instruments",
    "Portable digital laser distance meter with distance, area, volume, continuous measurement, Pythagorean calculation, addition and subtraction, and historical record functions.",
    "便携式数显激光测距仪，支持距离、面积、体积、连续测量、勾股测量、加减运算及历史记录功能。",
    [
      ["Multiple measuring ranges", "多种测量量程"],
      ["Accuracy ±(2mm+d*1/10000)", "精度±(2mm+d*1/10000)"],
      ["50 sets of historical records", "50组历史记录"],
    ],
    [
      ["Construction measurement", "建筑测量"],
      ["Interior layout", "室内测量"],
      ["Engineering survey", "工程勘测"],
    ],
    "4.jpg",
    ["4.1.jpg", "4.2.jpg", "4.3.jpg", "4.4.jpg", "4.5.jpg"],
    [
      ["Size", "120 × 52 × 28mm"],
      ["Range", "50m / 80m / 100m / 120m"],
      ["Accuracy", "±(2mm+d*1/10000)"],
      ["Laser Grade", "Class 2"],
      ["Unit", "m / ft / in"],
      ["Laser Wavelength", "620–690nm"],
      ["Laser Auto Shutdown", "30s"],
      ["Automatic Shutdown", "180s"],
      ["Benchmark", "Front and back"],
    ],
  ),

  make(
    5,
    "700m Mini GPS Golf Laser Rangefinder",
    "700米迷你高尔夫激光测距仪",
    "instruments",
    "Compact 6X mini golf laser rangefinder with high-sensitivity measurement, 5–700m range, IP54 weatherproof design, and built-in lithium battery.",
    "小型6倍高尔夫激光测距仪，具备高灵敏度测量、5–700米测距范围、IP54防护设计及内置锂电池。",
    [
      ["5–700m measuring range", "5–700米测量范围"],
      ["Accuracy ±1.0m + D*0.2%", "精度±1.0m + D*0.2%"],
      ["IP54 weatherproof rating", "IP54防护等级"],
    ],
    [
      ["Golf distance measurement", "高尔夫测距"],
      ["Outdoor ranging", "户外测距"],
      ["Sport field use", "运动场景使用"],
    ],
    "5.jpg",
    ["5.1.jpg", "5.2.jpg", "5.3.jpg", "5.4.jpg"],
    [
      ["Measuring Range", "5–700m"],
      ["Accuracy", "±1.0m + D*0.2%"],
      ["Magnification", "6X"],
      ["Dimensions", "136 × 108 × 60mm"],
      ["Protection", "IP54"],
      ["Battery", "Built-in lithium battery"],
    ],
  ),

  make(
    6,
    "HTC-2 LCD Digital Thermometer Hygrometer Weather Station",
    "HTC-2 LCD数显温湿度计气象站",
    "instruments",
    "LCD digital thermometer hygrometer weather station with indoor/outdoor temperature display, humidity monitoring, clock, calendar, alarm, and MAX/MIN memory function.",
    "HTC-2 LCD数显温湿度计气象站，支持室内外温度显示、湿度监测、时钟、日历、闹钟及最大/最小值记忆功能。",
    [
      ["Large LCD display", "大屏LCD显示"],
      ["Indoor and outdoor temperature display", "室内外温度显示"],
      ["Clock, calendar and alarm function", "时钟、日历与闹钟功能"],
    ],
    [
      ["Home environment monitoring", "家居环境监测"],
      ["Office temperature control", "办公室温湿度监测"],
      ["Storage room monitoring", "储藏环境监测"],
    ],
    "6.jpg",
    ["6.1.jpg", "6.2.jpg", "6.3.jpg", "6.4.jpg"],
    [
      ["Color", "White"],
      ["Temperature Range", "Indoor & Outdoor -50 ~ +70°C (-58 ~ +158°F)"],
      ["Humidity Range", "10% ~ 99% RH"],
      ["Humidity Accuracy", "±10% RH"],
      ["Power Supply", "1 × AAA battery"],
      ["Device Dimension", "10.5 × 9.8 × 2.4cm"],
      ["Device Weight", "126g"],
      ["Package Size", "18 × 13 × 4cm"],
      ["Package Weight", "162g"],
      ["Backlight", "No"],
    ],
  ),

  make(
    7,
    "Mini LCD Digital Thermometer Hygrometer",
    "迷你LCD数显温湿度计",
    "instruments",
    "Mini LCD digital thermometer hygrometer for indoor monitoring, fridge, freezer, egg incubator, and compact temperature and humidity checking applications.",
    "迷你LCD数显温湿度计，适用于室内监测、冰箱、冷柜、孵化器及小型温湿度检测场景。",
    [
      ["Compact mini size", "迷你小巧尺寸"],
      ["Temperature and humidity display", "温湿度双显示"],
      ["Fast humidity sampling", "快速湿度采样"],
    ],
    [
      ["Fridge and freezer monitoring", "冰箱冷柜监测"],
      ["Egg incubator use", "孵化器使用"],
      ["Indoor humidity monitoring", "室内湿度监测"],
    ],
    "7.jpg",
    ["7.1.jpg", "7.2.jpg", "7.3.jpg", "7.4.jpg", "7.5.jpg"],
    [
      ["Dimensions", "48 × 28.6 × 15.2mm"],
      ["LCD Size", "35.7 × 16.8mm"],
      ["Weight", "25g without battery"],
      ["Humidity Range", "10% to 99% RH"],
      ["Humidity Resolution", "1%"],
      ["Humidity Sampling Period", "10 seconds / 1 minute"],
      ["Humidity Accuracy", "±5%"],
      ["Rated Voltage", "DC1.5V, 2 × AG13 button batteries"],
      ["Temperature Range", "-50 to 70°C"],
      ["Temperature Accuracy", "±1°C at room temperature"],
    ],
  ),
    make(
    8,
    "Portable Automatic Bench Drilling Machine",
    "便携式自动台式钻孔机",
    "mechanical",
    "Compact automatic bench drilling machine designed for precision drilling work on metal, wood, plastic, and other hard materials in workshop and light industrial environments.",
    "小型自动台式钻孔机，适用于金属、木材、塑料及其他硬质材料的精密钻孔作业，可用于车间及轻型工业场景。",
    [
      ["High-precision drilling", "高精度钻孔"],
      ["Gear drive without belt design", "齿轮传动无皮带设计"],
      ["Power-off safety switch", "断电安全开关"],
    ],
    [
      ["Precision machining", "精密加工"],
      ["Workshop drilling", "车间钻孔"],
      ["Metal, wood and plastic processing", "金属、木材及塑料加工"],
    ],
    "8.jpg",
    ["8.1.jpg", "8.2.jpg", "8.3.jpg", "8.4.jpg", "8.5.jpg"],
    [
      ["Product Type", "Automatic Bench Drilling Machine"],
      ["Application", "Precision drilling and light machining"],
      ["Drive Type", "Gear drive without belt"],
      ["Suitable Materials", "Metal, wood, plastic and hard materials"],
      ["Safety Feature", "Power-off switch"],
      ["Structure", "Durable bench-mounted construction"],
    ],
  ),

  make(
    9,
    "Handheld Electric Metal Pipe Cutting Machine",
    "手持式电动金属管切割机",
    "mechanical",
    "Semi-automatic handheld electric pipe cutting machine designed for industrial metal cutting applications, suitable for carbon steel pipes and workshop cutting tasks.",
    "半自动手持式电动管材切割机，适用于工业金属切割应用，可用于碳钢管材及车间切割作业。",
    [
      ["Suitable for carbon steel pipe cutting", "适用于碳钢管切割"],
      ["Semi-automatic operation", "半自动操作"],
      ["Compact handheld structure", "紧凑手持式结构"],
    ],
    [
      ["Industrial metal cutting", "工业金属切割"],
      ["Pipe processing", "管材加工"],
      ["Workshop maintenance", "车间维护"],
    ],
    "9.jpg",
    ["9.jpg"],
    [
      ["Product Name", "Pipe Cutting Machine"],
      ["Cutting Range", "75–400mm"],
      ["Material Processed", "Carbon Steel"],
      ["Rated Power", "5 kW"],
      ["Voltage", "220 V"],
      ["Automation", "Semi-Automatic"],
      ["Core Component", "Gearbox"],
      ["Weight", "34 kg"],
      ["Package Size", "50 × 60 × 50 cm"],
      ["Gross Weight", "35 kg"],
    ],
  ),

  make(
    10,
    "Mini DC Gear Motor for Robot and Smart Devices",
    "机器人及智能设备用微型直流减速电机",
    "mechanical",
    "Mini brushed DC gear motor with compact size, stable torque output, and wide speed range, suitable for robots, smart locks, toys, small appliances, and precision electronic devices.",
    "微型有刷直流减速电机，结构紧凑、扭矩稳定、转速范围广，适用于机器人、智能锁、玩具、小型家电及精密电子设备。",
    [
      ["Compact 12mm motor frame", "12mm紧凑电机框架"],
      ["Wide speed range", "宽转速范围"],
      ["Stable torque output", "稳定扭矩输出"],
    ],
    [
      ["Robotics", "机器人应用"],
      ["Smart locks and RC cars", "智能锁及遥控车"],
      ["Toys and wearable devices", "玩具及可穿戴设备"],
    ],
    "10.jpg",
    ["10.1.jpg", "10.2.jpg", "10.3.jpg"],
    [
      ["Product Type", "Micro DC Gear Motor"],
      ["Motor Type", "Brush Motor"],
      ["Gear Type", "Square Gearbox"],
      ["Commutation", "Brush"],
      ["Construction", "Permanent Magnet"],
      ["Frame", "12mm"],
      ["Speed Range", "15–3000 RPM"],
      ["Efficiency", "65%"],
      ["Continuous Current", "120–260mA"],
      ["Torque", "15–500 g.cm / 0.015–0.5 kg.cm"],
      ["Motor Diameter", "12mm"],
      ["Shaft", "3mm"],
      ["Weight", "10g"],
      ["Package Size", "20 × 14 × 20 cm"],
      ["Gross Weight", "1 kg"],
    ],
  ),

  make(
    11,
    "CEMA Standard Steel Conveyor Roller",
    "CEMA标准钢制输送滚筒",
    "mechanical",
    "Heavy-duty steel conveyor roller designed for belt conveyor systems, suitable for ports, mines, coal plants, cement plants, quarries, and industrial material handling lines.",
    "重型钢制输送滚筒，适用于皮带输送系统，可用于港口、矿山、煤炭、水泥、采石场及工业物料输送线。",
    [
      ["Carbon steel roller tube", "碳钢滚筒管体"],
      ["Customizable diameter and length", "直径与长度可定制"],
      ["Suitable for heavy-duty conveyor systems", "适用于重型输送系统"],
    ],
    [
      ["Belt conveyor systems", "皮带输送系统"],
      ["Mining and quarry operations", "矿山及采石场作业"],
      ["Port and cement plant handling", "港口及水泥厂输送"],
    ],
    "11.jpg",
    ["11.1.jpg", "11.2.jpg", "11.3.jpg", "11.4.jpg", "11.5.jpg"],
    [
      ["Product Name", "Conveyor Roller"],
      ["Material", "Steel / Q235 / Q235B / Carbon Steel"],
      ["Applicable Industries", "Port, mine, coal, cement plant, quarry"],
      ["Diameter", "76–219mm"],
      ["Length", "190–3500mm"],
      ["Color", "OEM"],
      ["Bearing No.", "6204, 6205, 6305, 6306, 6307, 6308, 6309, 6310"],
      ["Standard", "ISO / DIN / Customer requirements"],
      ["Shaft Material", "Cold Drawing Round Steel"],
      ["Shaft Diameter", "20mm / 30mm / 35mm / 40mm / OEM"],
      ["Pipe Thickness", "3mm / 3.5mm / 4mm / OEM"],
      ["Package Size", "26 × 12 × 12 cm"],
      ["Gross Weight", "4 kg"],
    ],
  ),

  make(
    12,
    "150-Piece Magnetic Precision Screwdriver Repair Kit",
    "150件磁性精密螺丝刀维修套装",
    "mechanical",
    "150-piece magnetic precision screwdriver repair kit with aluminum alloy handle and interchangeable chrome-vanadium steel bits, suitable for DIY, industrial repair, electronics, and multi-purpose maintenance.",
    "150件磁性精密螺丝刀维修套装，配备铝合金手柄及可更换铬钒钢批头，适用于DIY、工业维修、电子设备及多功能维护场景。",
    [
      ["150-piece complete repair set", "150件完整维修套装"],
      ["Interchangeable magnetic bits", "可更换磁性批头"],
      ["Aluminum alloy handle", "铝合金手柄"],
    ],
    [
      ["Electronics repair", "电子产品维修"],
      ["Industrial maintenance", "工业维护"],
      ["DIY assembly and repair", "DIY组装与维修"],
    ],
    "12.jpg",
    ["12.1.jpg", "12.2.jpg", "12.3.jpg", "12.4.jpg", "12.5.jpg"],
    [
      ["Product Name", "150-piece screwdriver repair kit"],
      ["Number of Pieces", "150"],
      ["Screw Head Type", "Multipurpose"],
      ["Head Style", "Multi-bit screwdriver"],
      ["Bit Style", "Multipurpose Bit"],
      ["Handle Material", "Aluminum Alloy"],
      ["Blade Tip Material", "Chromium-Vanadium Steel"],
      ["Special Feature", "Interchangeable bit"],
      ["Grade", "DIY / Industrial"],
      ["Size", "153 × 107 × 54mm"],
      ["Customized Support", "OEM / ODM"],
      ["Application", "Multi-functional repair and assembly"],
    ],
  ),

  make(
    13,
    "41-in-1 Rechargeable Cordless Precision Electric Screwdriver Set",
    "41合1充电式无线精密电动螺丝刀套装",
    "mechanical",
    "41-in-1 rechargeable cordless precision electric screwdriver set with lithium-ion battery and brushless motor, designed for precision repair, assembly, and maintenance tasks.",
    "41合1充电式无线精密电动螺丝刀套装，配备锂电池与无刷电机，适用于精密维修、装配及维护作业。",
    [
      ["41-in-1 multifunctional set", "41合1多功能套装"],
      ["Rechargeable lithium-ion battery", "可充电锂离子电池"],
      ["Brushless motor design", "无刷电机设计"],
    ],
    [
      ["Precision electronics repair", "精密电子维修"],
      ["Household and industrial maintenance", "家用及工业维护"],
      ["Small equipment assembly", "小型设备装配"],
    ],
    "13.jpg",
    ["13.1.jpg", "13.2.jpg", "13.3.jpg", "13.4.jpg"],
    [
      ["Product Type", "Cordless Precision Electric Screwdriver Set"],
      ["Set Type", "41-in-1"],
      ["Grade", "Industrial"],
      ["Power Source", "Rechargeable lithium battery"],
      ["Motor Type", "Brushless Motor"],
      ["Max Torque", "5"],
      ["Voltage", "220V / 240V"],
      ["Battery Type", "Lithium-ion"],
      ["Weight", "0.693 kg"],
      ["Package Size", "19 × 11 × 6.5 cm"],
      ["Gross Weight", "0.990 kg"],
    ],
  ),

  make(
    14,
    "1500 Lumen LED Zoom Flashlight",
    "1500流明LED变焦手电筒",
    "mechanical",
    "Portable LED zoom flashlight with aluminum alloy body, adjustable beam focus, multiple lighting modes, and water-resistant design for inspection, camping, maintenance, and outdoor use.",
    "便携式LED变焦手电筒，采用铝合金机身，支持可调焦光束、多种照明模式及防水设计，适用于检查、露营、维护及户外使用。",
    [
      ["Adjustable zoom focus", "可调焦设计"],
      ["Aluminum alloy body", "铝合金机身"],
      ["Multiple lighting modes", "多种照明模式"],
    ],
    [
      ["Industrial inspection", "工业检查"],
      ["Outdoor camping", "户外露营"],
      ["Maintenance and emergency lighting", "维修及应急照明"],
    ],
    "14.jpg",
    ["14.1.jpg", "14.2.jpg", "14.3.jpg", "14.4.jpg", "14.5.jpg"],
    [
      ["Product Type", "LED Zoom Flashlight"],
      ["Light Source", "LED"],
      ["Lumen Class", "1500 Lumen Class"],
      ["Input Voltage", "DC 6V"],
      ["Power Source", "AA dry battery / USB rechargeable option"],
      ["Battery Type", "AA"],
      ["Battery Powered", "9 × AA batteries"],
      ["Material", "Aluminum Alloy"],
      ["Color Temperature", "6000K Daylight"],
      ["Working Modes", "High power / Low power / Strobe / SOS"],
      ["Lighting Distance", "Up to 300m"],
      ["Protection", "IP54 / IP67 option"],
      ["Product Size", "52 × 225mm"],
      ["Product Weight", "Approx. 0.3–0.346kg"],
      ["Lighting Period", "10–20 hours depending on mode"],
      ["Lifespan", "10000 hours"],
      ["Surface Treatment", "Anodized"],
      ["Package", "Color box"],
      ["Carton Quantity", "24PCS"],
      ["Carton Size", "48 × 44 × 44cm"],
      ["G.W. / N.W.", "13 / 12KG"],
    ],
  ),
    make(
    15,
    "520PCS 304 Stainless Steel Hex Bolt Nut Washer Assortment Kit",
    "520件304不锈钢六角螺栓螺母垫圈套装",
    "metal",
    "520-piece stainless steel hex bolt, nut, flat washer, and lock washer assortment kit packed in a clear storage box, suitable for industrial assembly, repair, construction fastening, and workshop spare parts.",
    "520件不锈钢六角螺栓、螺母、平垫圈及弹垫组合套装，配有透明分类收纳盒，适用于工业装配、维修、建筑紧固及车间备件使用。",
    [
      ["520-piece complete fastener kit", "520件完整紧固件套装"],
      ["304 stainless steel corrosion resistance", "304不锈钢防锈耐腐蚀"],
      ["Clear storage box with compartments", "透明分格收纳盒"],
    ],
    [
      ["Mechanical equipment assembly", "机械设备装配"],
      ["Workshop repair and maintenance", "车间维修与维护"],
      ["Construction and household fastening", "建筑及家用紧固"],
    ],
    "15.jpg",
    ["15.1.jpg", "15.2.jpg", "15.3.jpg", "15.4.jpg"],
    [
      ["Product Type", "Hex bolt, nut and washer assortment kit"],
      ["Pieces", "520PCS"],
      ["Main Material", "304 Stainless Steel"],
      ["Optional Materials", "Iron / Alloy Steel / Carbon Steel / Stainless Steel / Steel"],
      ["Grade", "Industrial"],
      ["Thread Type", "UNC / Standard thread option"],
      ["Head Type", "Hex Head Bolts"],
      ["Finish", "Zinc Plated / Plain"],
      ["Common Sizes", "M3 / M4 / M5 / M6"],
      ["Included Parts", "Bolts, nuts, flat washers, lock washers"],
      ["Storage", "Clear plastic organizer box"],
      ["Application", "Building, machinery repair, equipment assembly, DIY projects"],
    ],
  ),

  make(
    16,
    "700PCS Custom Nuts and Bolts Assortment Kit",
    "700件定制螺母螺栓组合套装",
    "metal",
    "700-piece customizable nuts, bolts, screws, and wire nut assortment kit designed for furniture installation, bed assembly, repair work, and general hardware fastening applications.",
    "700件可定制螺母、螺栓、螺丝及接线帽组合套装，适用于家具安装、床架装配、维修作业及通用五金紧固应用。",
    [
      ["700-piece assorted hardware kit", "700件五金组合套装"],
      ["Customizable screw head and thread options", "螺丝头型与螺纹可定制"],
      ["Suitable for metric and inch systems", "适用于公制及英制规格"],
    ],
    [
      ["Furniture installation", "家具安装"],
      ["Bed and frame assembly", "床架及框架装配"],
      ["Hardware repair and replacement", "五金维修与更换"],
    ],
    "16.jpg",
    ["16.1.jpg", "16.2.jpg", "16.3.jpg", "16.4.jpg", "16.5.jpg"],
    [
      ["Product Type", "Customized screw, nut and bolt set"],
      ["Pieces", "700PCS"],
      ["Measurement System", "Metric / Inch / Imperial"],
      ["Material Options", "Steel, stainless steel, brass, aluminum, copper, nylon, titanium and other options"],
      ["Strength Grade", "Class 4.8 / 6.8 / 8.8 option"],
      ["Thread Type", "Standard / Coarse / Fine thread options"],
      ["Head Style", "Hex, round, flat, truss, pan, oval and other options"],
      ["Screw Head Type", "Phillips / Slot / Torx / Flat / Multipurpose"],
      ["Thread Size", "M2 / M3 / M4 / M5 / M6 / M8 / M10 / M12 options"],
      ["Finish", "Nickel plated, galvanized, black oxide, zinc plated, anodized and other options"],
      ["Package Size", "20 × 15 × 4 cm"],
      ["Gross Weight", "1 kg"],
    ],
  ),

  make(
    17,
    "Stainless Steel Hex Socket Screw Fastener Combo Kit",
    "不锈钢内六角螺丝紧固件组合套装",
    "metal",
    "Stainless steel hex socket screw fastener combo kit with metric and inch measurement options, suitable for industrial equipment, mechanical installation, repair, and non-standard fastening applications.",
    "不锈钢内六角螺丝紧固件组合套装，支持公制及英制规格选择，适用于工业设备、机械安装、维修及非标紧固应用。",
    [
      ["Stainless steel fastener construction", "不锈钢紧固件结构"],
      ["Hex socket head design", "内六角头部设计"],
      ["Customized size support", "支持尺寸定制"],
    ],
    [
      ["Industrial equipment assembly", "工业设备装配"],
      ["Mechanical fastening", "机械紧固"],
      ["Repair and replacement work", "维修与更换作业"],
    ],
    "17.jpg",
    ["17.1.jpg", "17.2.jpg", "17.3.jpg", "17.4.jpg", "17.5.jpg"],
    [
      ["Product Type", "Hex socket screw fastener combo kit"],
      ["Measurement System", "Inch / Metric"],
      ["Material", "Stainless Steel"],
      ["Material Grade", "18-8 / 304 / 316 options"],
      ["Thread Type", "Standard Thread"],
      ["Head Style", "Hex Socket"],
      ["Finish", "Black / Zinc option"],
      ["Size", "Customized"],
      ["Surface Treatment", "Polishing"],
      ["Standard", "Standard / Non-standard options"],
      ["Application", "Industrial Equipment"],
      ["Packing", "Box Packing"],
      ["Package Size", "2 × 2 × 8 cm"],
      ["Gross Weight", "1 kg"],
    ],
  ),

  make(
    18,
    "6000 Series Extruded Aluminium L Shape Angle Profile",
    "6000系列挤压铝合金L型角铝型材",
    "metal",
    "6000 series extruded aluminium L-shape angle profile with customizable size, finish, and processing options, suitable for construction, industrial structures, decorative frames, doors, windows, and CNC deep-processing applications.",
    "6000系列挤压铝合金L型角铝型材，支持尺寸、表面处理及加工方式定制，适用于建筑、工业结构、装饰框架、门窗及CNC深加工应用。",
    [
      ["6000 series aluminium alloy", "6000系列铝合金"],
      ["Customizable size and finish", "尺寸与表面处理可定制"],
      ["Supports bending, welding, punching and cutting", "支持折弯、焊接、冲孔及切割加工"],
    ],
    [
      ["Construction profiles", "建筑型材"],
      ["Industrial frames", "工业框架"],
      ["Decorative and CNC processed parts", "装饰及CNC深加工部件"],
    ],
    "18.jpg",
    ["18.1.jpg", "18.2.jpg", "18.3.jpg", "18.4.jpg", "18.5.jpg"],
    [
      ["Product Type", "Extruded aluminium L-shape angle profile"],
      ["Grade", "6000 Series / 7000 Series option"],
      ["Shape", "L Shape / Special Shape"],
      ["Temper", "T3–T8"],
      ["Tolerance", "±0.01mm / ±0.1mm option"],
      ["Material", "Aluminum alloy / stainless steel / brass / bronze / copper options"],
      ["Thickness", "0.4mm–500mm option"],
      ["Size", "Customized"],
      ["Color", "Red, green, blue, silver, black and customized colors"],
      ["Finish", "Anodizing, sandblasting, powder coating, polishing, brushed, wood grain, electrophoresis"],
      ["Processing Service", "Bending, welding, punching, cutting"],
      ["Application Range", "Doors, windows, architectural, industrial, decorative and CNC aluminum profiles"],
      ["Package Size", "30 × 10 × 10 cm"],
      ["Gross Weight", "2 kg"],
    ],
  ),

  make(
    19,
    "90 Degree Aluminum Extrusion Corner Bracket",
    "90度铝型材角码连接件",
    "metal",
    "90-degree aluminum extrusion corner bracket designed for 2020, 3030, and 4040 aluminum profile systems, suitable for modular frames, machine guards, equipment racks, and structural assembly.",
    "90度铝型材角码连接件，适用于2020、3030及4040铝型材系统，可用于模块化框架、机器防护罩、设备架及结构装配。",
    [
      ["90-degree corner connection", "90度角连接"],
      ["Compatible with 2020/3030/4040 profiles", "兼容2020/3030/4040型材"],
      ["Die-cast aluminum structure", "压铸铝结构"],
    ],
    [
      ["Aluminum extrusion frames", "铝型材框架"],
      ["Machine guarding systems", "机器防护系统"],
      ["Equipment rack assembly", "设备架装配"],
    ],
    "19.jpg",
    ["19.1.jpg", "19.2.jpg", "19.3.jpg"],
    [
      ["Product Type", "Angle bracket / Corner bracket"],
      ["Bracket Type", "Triangle Bracket / Single-Side Bracket"],
      ["Angle", "90 Degree"],
      ["Compatible Profiles", "2020 / 3030 / 4040 aluminum extrusion"],
      ["Material", "Die-cast Aluminum"],
      ["Surface Treatment", "Polished"],
      ["Finish", "Natural"],
      ["Standard", "Standard"],
      ["Model Options", "20ZJ-6 / 30ZJ / 40ZJ-8"],
      ["Package Size", "45 × 20 × 35 cm"],
      ["Gross Weight", "1 kg"],
    ],
  ),

  make(
    20,
    "3-Way 90 Degree Aluminum Square Tube Corner Connector",
    "三通90度铝合金方管角连接件",
    "metal",
    "3-way 90-degree aluminum square tube corner connector designed for square pipe connection, racking, modular structures, display frames, and lightweight assembly systems.",
    "三通90度铝合金方管角连接件，适用于方管连接、货架、模块化结构、展示框架及轻型装配系统。",
    [
      ["3-way 90-degree square tube connection", "三通90度方管连接"],
      ["Aluminum alloy clamp structure", "铝合金夹紧结构"],
      ["Suitable for modular racking systems", "适用于模块化货架系统"],
    ],
    [
      ["Square tube structure assembly", "方管结构装配"],
      ["Racking and display frames", "货架及展示框架"],
      ["Modular pipe connection", "模块化管材连接"],
    ],
    "20.jpg",
    ["20.1.jpg", "20.2.jpg", "20.3.jpg", "20.4.jpg", "20.5.jpg"],
    [
      ["Product Type", "Aluminum square tube corner connector"],
      ["Connection Type", "Clamp with screw"],
      ["Connector Type", "3-Way / 90 Degree"],
      ["Material", "Aluminum Alloy"],
      ["Color", "Silver / Natural silver / Black option"],
      ["Surface", "Natural Aluminum Silver"],
      ["Shape", "Equal Square"],
      ["Size Options", "20 × 20mm / 25 × 25mm / 30 × 30mm"],
      ["Mounting Hole Diameter", "20 / 25 / 30"],
      ["Testing Pressure", "100kg"],
      ["Application", "Racking, pipe connection and structural fittings"],
      ["Package Size", "10 × 5 × 10 cm"],
      ["Gross Weight", "1.5 kg"],
    ],
  ),

  make(
    21,
    "Aluminum Profile T-Slot Anchor Joint Connector",
    "铝型材T槽锚式连接件",
    "metal",
    "T-slot anchor joint connector for aluminum profile modular assembly systems, suitable for industrial frames, conveyor systems, stair and platform systems, machine guarding, and profile accessories.",
    "铝型材T槽锚式连接件，适用于铝型材模块化装配系统，可用于工业框架、输送系统、楼梯平台系统、机器防护及型材配件。",
    [
      ["Designed for aluminum profile assembly systems", "适用于铝型材装配系统"],
      ["T-slot anchor joint connection", "T槽锚式连接结构"],
      ["Compact modular connector", "小型模块化连接件"],
    ],
    [
      ["Aluminum profile frames", "铝型材框架"],
      ["Conveyor and platform systems", "输送及平台系统"],
      ["Machine guarding structures", "机器防护结构"],
    ],
    "21.jpg",
    ["21.1.jpg", "21.2.jpg", "21.3.jpg", "21.4.jpg", "21.5.jpg"],
    [
      ["Product Type", "T-slot anchor joint connector"],
      ["Profile Group", "Connectors"],
      ["Series", "Modular Assembly System"],
      ["Material", "Aluminum alloy / Zinc plated carbon steel option"],
      ["Color", "Silver"],
      ["Shape", "T-Profile"],
      ["Temper", "T3–T8 option"],
      ["Tolerance", "±1%"],
      ["Processing Service", "Bending, decoiling, welding, punching, cutting"],
      ["Application", "Industrial modular assembly system"],
      ["System Lines", "Aluminum profile assembly, conveyor system, stair and platform system, machine guarding, components and accessories"],
      ["Package Size", "7 × 5 × 4 cm"],
      ["Gross Weight", "0.4 kg"],
    ],
  ),
    make(
    22,
    "Waterproof Adhesive Thermal Shipping Label Sticker Paper",
    "防水热敏不干胶运单标签纸",
    "office",
    "Waterproof self-adhesive thermal label sticker paper designed for waybill labels, packaging labels, and business shipping applications. Suitable for thermal printing and rectangular label use.",
    "防水热敏不干胶标签纸，适用于运单标签、包装标签及商业物流场景，适合热敏打印及矩形标签应用。",
    [
      ["Waterproof adhesive thermal label", "防水不干胶热敏标签"],
      ["Suitable for shipping and packaging labels", "适用于物流与包装标签"],
      ["Supports multiple printing methods", "支持多种印刷方式"],
    ],
    [
      ["Waybill and shipping labels", "运单及物流标签"],
      ["Packaging and warehouse marking", "包装及仓储标识"],
      ["Business and retail labeling", "商业与零售标签"],
    ],
    "22.jpg",
    ["22.1.jpg", "22.2.jpg", "22.3.jpg", "22.4.jpg", "22.5.jpg"],
    [
      ["Product Type", "Waterproof self-adhesive packaging label sticker"],
      ["Industrial Use", "Business & Shopping / Promotion"],
      ["Material", "Thermal Paper"],
      ["Type", "Adhesive Sticker"],
      ["Feature", "Anti-counterfeit / Waterproof"],
      ["Printing Handling", "Color Printing, Offset Printing, Thermal Transfer Printing, Thermal Printing, UV Printing, Stamping"],
      ["Label Shape", "Rectangular"],
      ["Size Options", "30×20mm / 40×20mm / 40×30mm"],
      ["Custom Order", "Accepted"],
      ["Package Size", "10 × 10 × 10 cm"],
      ["Gross Weight", "2 kg"],
    ],
  ),

  make(
    23,
    "Thermal POS Cash Register Receipt Paper Roll",
    "热敏POS收银纸卷",
    "office",
    "Thermal paper roll for POS systems, cash registers, receipt printers, ticket printers, and ATM printing applications. Available in multiple widths and grammage options.",
    "热敏纸卷，适用于POS系统、收银机、小票打印机、票据打印机及ATM打印应用，提供多种宽度和克重选择。",
    [
      ["Suitable for POS and cash register printing", "适用于POS及收银打印"],
      ["Made from thermal paper / wood pulp", "采用热敏纸/木浆材料"],
      ["Available in multiple roll sizes", "提供多种卷纸规格"],
    ],
    [
      ["Cash register receipt printing", "收银小票打印"],
      ["POS and ATM paper use", "POS及ATM用纸"],
      ["Retail and ticket printing", "零售及票据打印"],
    ],
    "23.jpg",
    ["23.1.jpg", "23.2.jpg", "23.3.jpg", "23.4.jpg"],
    [
      ["Product Type", "Thermal paper roll / Receipt paper roll / POS paper"],
      ["Paper Type", "Thermal Paper"],
      ["Layer Quantity", "Single"],
      ["Common Sizes", "57×40mm / 57×50mm / 57×30mm / 80×80mm"],
      ["Material", "100% Wood Pulp"],
      ["Grammage", "48–80gsm"],
      ["Core", "Paper Core / Cardboard Core"],
      ["Usage", "Cash Register Printer / POS / ATM Printer"],
      ["MOQ", "1000 Rolls"],
      ["Package Size", "8 × 8 × 5 cm"],
      ["Gross Weight", "0.032 kg"],
    ],
  ),

  make(
    24,
    "Mini 58mm USB POS Thermal Receipt Printer",
    "迷你58mm USB热敏小票打印机",
    "office",
    "Compact 58mm desktop thermal receipt printer with USB connectivity, thermal line printing, ESC/POS compatibility, and support for barcode and QR code printing.",
    "紧凑型58mm桌面热敏小票打印机，支持USB连接、热敏行式打印、ESC/POS指令及条码与二维码打印。",
    [
      ["Compact 58mm desktop printer", "紧凑型58mm桌面打印机"],
      ["USB thermal line printing", "USB热敏行式打印"],
      ["Supports 1D barcode and QR code printing", "支持一维码及二维码打印"],
    ],
    [
      ["POS receipt printing", "POS小票打印"],
      ["Retail counter use", "零售收银场景"],
      ["Small business transaction printing", "中小商户票据打印"],
    ],
    "24.jpg",
    ["24.1.jpg", "24.2.jpg", "24.3.jpg", "24.4.jpg", "24.5.jpg"],
    [
      ["Application", "Receipt Printer"],
      ["Max Paper Size", "58mm"],
      ["Printing Method", "Thermal Line Printing"],
      ["Resolution", "203dpi (8 dots/mm)"],
      ["Printing Speed", "Max 90mm/s"],
      ["Effective Printing Width", "48mm"],
      ["Paper Width", "58mm"],
      ["Paper Diameter", "60mm Max"],
      ["Paper Thickness", "55–90μm"],
      ["Interface", "USB / USB+Bluetooth option / Cash Drawer"],
      ["Power", "DC12V / 2A to 2.6A"],
      ["Cashbox Control", "DC12V / 1A"],
      ["Command", "Compatible with ESC/POS command set"],
      ["Drivers", "Windows / Linux / OPOS"],
      ["Dimensions", "Approx. 120×150×111.5mm / 135×120×112mm"],
      ["Package Size", "20 × 20 × 18 cm"],
      ["Gross Weight", "2 kg"],
    ],
  ),

  make(
    25,
    "Portable Direct Thermal Barcode Label Printer",
    "便携式热敏条码标签打印机",
    "office",
    "Portable direct thermal barcode label printer with 203dpi resolution, USB interface, and support for shipping labels, stock labels, barcode labels, and transport label printing.",
    "便携式热敏条码标签打印机，分辨率203dpi，支持USB连接，可用于物流标签、库存标签、条码标签及运输标签打印。",
    [
      ["Portable direct thermal printing", "便携式热敏打印"],
      ["203dpi barcode and label output", "203dpi条码与标签打印"],
      ["Suitable for shipping and stock labels", "适用于物流及库存标签"],
    ],
    [
      ["Shipping label printing", "物流标签打印"],
      ["Stock and warehouse labeling", "库存及仓储标签"],
      ["Barcode label printing", "条码标签打印"],
    ],
    "25.jpg",
    ["25.1.jpg", "25.2.jpg", "25.3.jpg", "25.4.jpg"],
    [
      ["Application", "Thermal Label Printer / Barcode Printer"],
      ["Print Technology", "Direct Thermal"],
      ["Max Resolution", "203 dpi"],
      ["Print Speed", "150mm/s"],
      ["Max Paper Size", "Up to 110mm"],
      ["Paper Type", "Thermal Paper"],
      ["Connection Type", "USB / Bluetooth / Wireless / Mobile App"],
      ["Interface", "USB + BT Wireless"],
      ["Product Size", "185 × 74 × 75mm"],
      ["Power", "24V / 2.5A"],
      ["Use", "Shipping Label / Transport Label / Barcode Label"],
      ["Package Size", "23 × 16 × 11 cm"],
      ["Gross Weight", "1.3 kg"],
    ],
  ),

  make(
    26,
    "110mm Wireless Thermal Shipping Label Printer",
    "110mm无线热敏物流标签打印机",
    "office",
    "Wireless 110mm thermal shipping label printer with 203dpi resolution, direct thermal technology, and support for barcode, shipping, and retail label printing.",
    "110mm无线热敏物流标签打印机，分辨率203dpi，采用热敏打印技术，适用于条码、物流及零售标签打印。",
    [
      ["Supports 110mm label printing", "支持110mm标签打印"],
      ["Wireless thermal printing", "无线热敏打印"],
      ["Suitable for shipping and barcode labels", "适用于物流及条码标签"],
    ],
    [
      ["Shipping label printing", "物流标签打印"],
      ["Retail shop barcode labeling", "零售门店条码标签"],
      ["Warehouse and ecommerce packaging", "仓储及电商包装标签"],
    ],
    "26.jpg",
    ["26.1.jpg", "26.2.jpg", "26.3.jpg", "26.4.jpg"],
    [
      ["Application", "Label Maker / Barcode Printer"],
      ["Max Paper Size", "110mm"],
      ["Paper Width", "37–108mm"],
      ["Print Technology", "Direct Thermal"],
      ["Max Resolution", "203 dpi"],
      ["Print Speed", "150mm/s"],
      ["Paper Type", "Thermal Paper"],
      ["Connection Type", "Bluetooth / USB / Wireless / Mobile App"],
      ["Charging Interface", "24V / 2.5A"],
      ["Product Size", "185 × 74 × 75mm"],
      ["Style", "Black and White"],
      ["Package Size", "30 × 20 × 20 cm"],
      ["Gross Weight", "1.3 kg"],
    ],
  ),

  make(
    27,
    "High-Speed 80mm Thermal Barcode Sticker Printer",
    "高速80mm热敏条码标签打印机",
    "office",
    "High-speed 80mm thermal barcode sticker printer with 203dpi resolution, USB interface, and support for label, barcode, and POS printing across desktop business environments.",
    "高速80mm热敏条码标签打印机，分辨率203dpi，支持USB连接，可用于标签、条码及POS打印，适合桌面商业环境使用。",
    [
      ["High-speed 80mm thermal printing", "高速80mm热敏打印"],
      ["Supports barcode and sticker labels", "支持条码及不干胶标签打印"],
      ["Wide compatibility for desktop systems", "适配多种桌面系统"],
    ],
    [
      ["Barcode label printing", "条码标签打印"],
      ["POS and sticker printing", "POS及不干胶打印"],
      ["Retail and logistics use", "零售及物流应用"],
    ],
    "27.jpg",
    ["27.1.jpg", "27.2.jpg", "27.3.jpg"],
    [
      ["Product Type", "Thermal Barcode Sticker Printer"],
      ["Model", "GP3120TL"],
      ["Max Resolution", "203 dpi (8 dots/mm)"],
      ["Black Print Speed", "5 inch/sec / 100–127 mm/s"],
      ["Max Paper Size", "8cm"],
      ["Print Width", "2–8cm"],
      ["Printing Method", "Thermal Transfer Print"],
      ["Paper Width", "16mm to 82mm"],
      ["Paper Thickness", "0.06–0.08mm"],
      ["Interface", "USB / Parallel / Serial Port"],
      ["Power", "DC 24V / 3A"],
      ["Cash Drawer Control", "DC 12V / 1A"],
      ["Automatic Cutter", "Full or Partial Cut"],
      ["Reliability", "100 KM"],
      ["Printer Size", "220 × 150 × 150mm"],
      ["Weight", "2 kg"],
      ["Package Size", "27 × 23 × 25 cm"],
      ["Gross Weight", "3 kg"],
    ],
  ),

  make(
    28,
    "A4 Duplex Color Document Scanner",
    "A4双面彩色文件扫描仪",
    "office",
    "High-speed duplex color document scanner designed for business and professional document processing, with USB connectivity, sharp image output, and reliable feeding for office scanning tasks.",
    "高速双面彩色文件扫描仪，适用于商务及专业文档处理，支持USB连接、清晰图像输出及稳定进纸，适合办公室扫描任务。",
    [
      ["Duplex double-sided scanning", "支持双面扫描"],
      ["High-speed document processing", "高速文档处理"],
      ["Sharp color image output", "清晰彩色图像输出"],
    ],
    [
      ["Office document digitization", "办公文件数字化"],
      ["Legal, healthcare and finance scanning", "法律、医疗及金融文档扫描"],
      ["A4 business document processing", "A4商务文件处理"],
    ],
    "28.jpg",
    ["28.1.jpg", "28.2.jpg", "28.3.jpg", "28.4.jpg", "28.5.jpg"],
    [
      ["Type", "Document Scanner"],
      ["Paper Size", "A4"],
      ["Scan Element Type", "CIS"],
      ["Color Depth", "32 Bit"],
      ["Interface", "USB 2.0 / Wireless support depending on version"],
      ["Scanning Speed", "Up to 50 ppm / 100 ipm duplex"],
      ["Resolution", "Up to 600 dpi"],
      ["Function", "Duplex double-sided color document scanning"],
      ["Feeding", "Reliable feeding with double-feed detection"],
      ["Paper Support", "Up to 209 g/m² paper, including business cards and thick paper"],
      ["Use", "Business / professional document scanning"],
      ["Color", "Black"],
    ],
  ),
];

export const findProduct = (slug: string) => PRODUCTS.find((p) => p.slug === slug);
